name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base_indepth: true
          plugin_lines: true
          plugin_languages: true
          plugin_languages_ignored: html, css
          plugin_traffic: true
          plugin_topics: true
          plugin_topics_mode: labels
          plugin_calendar: true
          plugin_calendar_limit: 0
          plugin_starlists: true
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year

